_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.19
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
cov_lat:
    value: 100
cov_up:
    value: 1
epochs:
    value: 40000
seqdim:
    value: 1000
